version: '3.8'

services:
  mcp-sequential:
    image: mcp/sequentialthinking
    networks:
      - mcp-network
    stdin_open: true
    tty: true
    command: ["node", "dist/index.js"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "node"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mcp-network:
    driver: bridge

volumes:
  mcp-data:
    driver: local